const lessons=[
{n:1,icon:'❤',theme:'theme-1',title:'O Plano da Salvação',subtitle:'O amor de Deus revelado em Jesus Cristo.',gold:'“Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito...”',ref:'João 3:16',objectives:['Compreender o amor de Deus e Seu plano de salvação.','Reconhecer que todos necessitam da salvação.','Entender que Jesus Cristo é o único Salvador.','Aprender como receber a salvação pela fé.'],learn:['O amor de Deus pela humanidade.','O problema do pecado.','A missão de Jesus Cristo.','O significado da salvação.','Como receber a salvação.','A nova vida do discípulo.'],readings:[['Segunda','João 3'],['Terça','Romanos 3'],['Quarta','Romanos 5'],['Quinta','Efésios 2'],['Sexta','Isaías 53'],['Sábado','Lucas 15'],['Domingo','João 10']],intro:'Deus criou o ser humano para viver em comunhão com Ele. O pecado separou a humanidade de Deus, mas, por amor, o Senhor enviou Jesus Cristo para oferecer perdão, reconciliação e uma nova vida.',did:'A palavra salvação comunica a ideia de resgate. Em Jesus, Deus nos oferece perdão dos pecados, reconciliação e vida eterna.',apply:'Agradeça a Deus pela salvação e escolha uma pessoa para quem você possa falar sobre o amor de Jesus nesta semana.',prayer:'Senhor Jesus, obrigado pelo Teu amor e pela salvação. Ajuda-me a viver como Teu discípulo e a compartilhar o Evangelho. Amém.',questions:['Quem enviou Jesus ao mundo?','Por que precisamos da salvação?','Como recebemos a salvação?','O que significa ser discípulo?','O que Deus falou ao seu coração?']},
{n:2,icon:'📖',theme:'theme-2',title:'A Bíblia: A Palavra de Deus',subtitle:'A verdade que ilumina, ensina e transforma.',gold:'“Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a educação na justiça.”',ref:'2 Timóteo 3:16',objectives:['Compreender que a Bíblia é a Palavra inspirada por Deus.','Conhecer sua importância para a vida cristã.','Desenvolver o hábito da leitura diária.','Reconhecer a Bíblia como regra de fé e prática.'],learn:['O que é a Bíblia.','Como a Bíblia foi inspirada.','Por que devemos lê-la.','Como compreender as Escrituras.','Como praticar a Palavra.','A Bíblia na vida diária.'],readings:[['Segunda','Salmo 119:105'],['Terça','2 Timóteo 3:16-17'],['Quarta','Hebreus 4:12'],['Quinta','Josué 1:8'],['Sexta','Salmo 1:1-3'],['Sábado','João 5:39'],['Domingo','Mateus 7:24-27']],intro:'A Bíblia é a Palavra de Deus revelada à humanidade. Nela conhecemos o caráter de Deus, o plano da salvação e os ensinamentos necessários para uma vida cristã firme.',did:'Durante a Reforma Protestante, Martinho Lutero traduziu a Bíblia para o alemão usando principalmente textos em hebraico e grego, tornando as Escrituras mais acessíveis ao povo.',apply:'Escolha um horário fixo para ler a Bíblia todos os dias. Comece com poucos versículos e anote uma verdade que aprendeu.',prayer:'Senhor, dá-me amor pela Tua Palavra. Ajuda-me a compreender, guardar e praticar o que leio. Amém.',questions:['Por que a Bíblia é importante?','O que significa dizer que ela é inspirada por Deus?','Como criar o hábito da leitura bíblica?','Qual texto falou mais ao seu coração?']},
{n:3,icon:'🙏',theme:'theme-3',title:'A Oração',subtitle:'Falando com Deus todos os dias.',gold:'“Orai sem cessar.”',ref:'1 Tessalonicenses 5:17',objectives:['Compreender o que é a oração.','Reconhecer a importância de falar com Deus diariamente.','Desenvolver o hábito da oração.','Confiar que Deus ouve as orações.'],learn:['O que é a oração.','Por que devemos orar.','Como Jesus nos ensinou.','Como a oração fortalece a fé.','Como Deus responde.','Como viver em oração.'],readings:[['Segunda','Mateus 6:5-8'],['Terça','Mateus 6:9-13'],['Quarta','Lucas 11:1-4'],['Quinta','Filipenses 4:6-7'],['Sexta','1 Tessalonicenses 5:17-18'],['Sábado','Tiago 5:16'],['Domingo','Salmo 145:18']],intro:'A oração é um presente de Deus para fortalecer nosso relacionamento com Ele. Por meio dela conversamos com o Senhor, agradecemos, adoramos e apresentamos nossos pedidos.',did:'George Müller viveu na Inglaterra no século XIX e dedicou sua vida a cuidar de milhares de crianças órfãs. Sua vida tornou-se um exemplo de confiança em Deus por meio da oração.',apply:'Escolha um horário do dia para falar com Deus. Use suas próprias palavras e continue orando mesmo quando a resposta não vier imediatamente.',prayer:'Senhor Deus, ensina-me a falar Contigo com sinceridade. Ajuda-me a confiar em Ti e buscar Tua direção todos os dias. Amém.',questions:['O que significa orar com sinceridade?','Em quais momentos você costuma falar com Deus?','Como a oração fortalece a fé?','O que Jesus nos ensinou sobre oração?']},
{n:4,icon:'⛪',theme:'theme-4',title:'A Igreja e a Comunhão Cristã',subtitle:'Unidos como um só corpo em Cristo.',gold:'“Assim nós, que somos muitos, somos um só corpo em Cristo e membros uns dos outros.”',ref:'Romanos 12:5',objectives:['Compreender o que é a Igreja de Cristo.','Entender a importância da comunhão entre os irmãos.','Desenvolver o compromisso de participar da vida da igreja.','Valorizar a unidade do Corpo de Cristo.'],learn:['O que é a Igreja.','A Igreja como Corpo de Cristo.','A importância da comunhão cristã.','Os benefícios de congregar.','Servindo uns aos outros com amor.','Vivendo em unidade.'],readings:[['Segunda','Atos 2:42-47'],['Terça','Hebreus 10:24-25'],['Quarta','Efésios 4:1-6'],['Quinta','Romanos 12:4-5'],['Sexta','1 Coríntios 12:12-27'],['Sábado','Salmo 133'],['Domingo','João 13:34-35']],intro:'A Igreja não é apenas um prédio onde as pessoas se reúnem. A verdadeira Igreja é formada por todos aqueles que receberam Jesus Cristo como Salvador. Deus nos chamou para vivermos em comunhão, aprendendo Sua Palavra e servindo uns aos outros com amor.',did:'A palavra igreja vem do termo grego ekklesia, que significa “os chamados para fora” ou “assembleia dos chamados”. Participar da igreja fortalece nossa fé, promove comunhão e nos ajuda a permanecer firmes.',apply:'Participe ativamente da igreja nesta semana. Cumprimente alguém, ore por uma pessoa e procure uma maneira simples de servir.',prayer:'Senhor, ensina-me a amar Tua Igreja, viver em comunhão e servir meus irmãos com humildade e alegria. Amém.',questions:['O que é a Igreja segundo a Bíblia?','Por que não devemos caminhar sozinhos?','Como podemos servir uns aos outros?','O que significa viver em unidade?']}
];
const screens=[...document.querySelectorAll('.screen')],nav=[...document.querySelectorAll('.bottom-nav button')];
const $=s=>document.querySelector(s);
function go(name){screens.forEach(x=>x.classList.toggle('active',x.dataset.screen===name));nav.forEach(x=>x.classList.toggle('active',x.dataset.go===name));scrollTo({top:0,behavior:'smooth'});}
function card(l,compact=false){return `<article class="${compact?'lesson-list-card':'lesson-card'} ${l.theme}">${compact?`<div class="round-icon">${l.icon}</div><div><small>LIÇÃO ${l.n}</small><h3>${l.title}</h3><p>${l.subtitle}</p></div><button data-open-lesson="${l.n}">→</button>`:`<div><div class="icon">${l.icon}</div><small>LIÇÃO ${l.n}</small><h3>${l.title}</h3><p>${l.subtitle}</p></div><button data-open-lesson="${l.n}">Abrir lição</button>`}</article>`}
$('#homeLessons').innerHTML=lessons.map(l=>card(l)).join('');
$('#lessonGrid').innerHTML=lessons.map(l=>card(l,true)).join('')+`<article class="lesson-list-card" style="background:linear-gradient(145deg,#577081,#8fa8b5)"><div class="round-icon">💧</div><div><small>PRÓXIMA ETAPA</small><h3>Lições 5, 6 e 7</h3><p>Conteúdo será inserido conforme a revista for concluída.</p></div><button disabled>🔒</button></article>`;
function renderLesson(n){const l=lessons.find(x=>x.n===Number(n));if(!l)return;$('#readerContent').innerHTML=`<header class="reader-top ${l.theme}"><button data-back>← Voltar</button><small>LIÇÃO ${l.n}</small><h1>${l.title}</h1><p>${l.subtitle}</p></header><nav class="part-tabs">${['Início','Conteúdo','Leitura','Aplicação','Atividade'].map((x,i)=>`<button class="${i===0?'active':''}" data-part="${i}">${x}</button>`).join('')}</nav>
<section class="reader-page active" data-page="0"><div class="content-card"><div class="student-box"><b>Data da Aula: ____/____/______</b><span>Professor(a): ____________________</span><span>Aluno(a): ________________________</span><span>Presença: ( ) Presente &nbsp; ( ) Ausente</span></div><h3>Pedido de Oração</h3><div class="answer-line"></div><div class="answer-line"></div></div><div class="content-card gold-box"><h3>Texto-Áureo</h3><blockquote>${l.gold}</blockquote><strong>${l.ref}</strong></div><div class="content-card"><h3>Objetivos da Lição</h3><ul>${l.objectives.map(x=>`<li>${x}</li>`).join('')}</ul></div></section>
<section class="reader-page" data-page="1"><div class="content-card"><h2>Nesta lição você aprenderá</h2><ol>${l.learn.map((x,i)=>`<li><b>${l.n}.${i+1}</b> ${x}</li>`).join('')}</ol></div><div class="content-card"><h2>Introdução</h2><p>${l.intro}</p></div><div class="content-card green-box"><h3>Você Sabia?</h3><p>${l.did}</p></div></section>
<section class="reader-page" data-page="2"><div class="content-card"><h2>Leitura Bíblica da Semana</h2><table class="reading-table"><thead><tr><th>Dia</th><th>Leitura</th><th>Li</th><th>Orei</th></tr></thead><tbody>${l.readings.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>□</td><td>□</td></tr>`).join('')}</tbody></table></div></section>
<section class="reader-page" data-page="3"><div class="content-card green-box"><h2>Aplicando à Minha Vida</h2><p>${l.apply}</p></div><div class="content-card"><h2>Momento de Oração</h2><p>${l.prayer}</p></div><div class="content-card"><h3>Minha anotação</h3><div class="answer-line"></div><div class="answer-line"></div><div class="answer-line"></div></div></section>
<section class="reader-page" data-page="4"><div class="content-card"><h2>Pense e responda</h2>${l.questions.map((q,i)=>`<div class="question"><b>${i+1}. ${q}</b><div class="answer-line"></div><div class="answer-line"></div></div>`).join('')}</div><button class="complete-btn" data-complete="${l.n}">✓ Concluir esta lição</button></section>`;go('reader');bindReader();}
function bindReader(){document.querySelector('[data-back]').onclick=()=>go('lessons');document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-part]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===b.dataset.part));});document.querySelector('[data-complete]').onclick=e=>{localStorage.setItem(`lesson-${e.currentTarget.dataset.complete}`,'done');e.currentTarget.textContent='🎉 Lição concluída!';e.currentTarget.disabled=true;};}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open-lesson]');if(open)renderLesson(open.dataset.openLesson);const g=e.target.closest('[data-go]');if(g)go(g.dataset.go);});
$('#printBtn').onclick=()=>window.print();
